version: "3.9"  # optional since v1.27.0

networks:
  primes-net:
    driver: bridge

services:
  # Web App served via lighttpd
  web:
    build: lighttpd/
    ports:
      - "8080:8080"
    networks:
      - primes-net
    depends_on:
      - "api" # make sure API is up so that proxy doesn't fail

  # Web API served via Quarkus
  api:
    #image: primes/prime-api/quarkus:latest
    build:
      context: ./quarkus-api/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    networks:
      - primes-net