version: "3.9"  # optional since v1.27.0

networks:
  primes-net:
    driver: bridge

services:
  # "REST" api with .Net Core 3.1, build on container
  api:
    build: rest-api/
    # ports:
    #   - "5000:5000"
    networks:
      - primes-net
    command: --urls http://api:5000
    # volumes:
    #   # timezone fix (doesn't wrok on windows)
    #   - "/etc/timezone:/etc/timezone:ro"
    #   - "/etc/localtime:/etc/localtime:ro"

  # web app served via lighty
  web:
    image: registry.gitlab.com/s.teumert/docker-lighttpd:1.0.0
    ports:
      - "8080:8080"
    networks:
      - primes-net
    depends_on:
      - "api" # make sure API is up so that proxy doesn't fail
    volumes:
      - "./web-app/dist:/var/www/localhost/htdocs/"
      - "./lighttpd:/etc/lighttpd/"
      # timezone fix
    #   - "/etc/timezone:/etc/timezone:ro"
    #   - "/etc/localtime:/etc/localtime:ro"

#   # web app served via webpack
#   web:
#     build: web-app/
#     ports:
#       - "8080:8080"
#     networks:
#       - primes-net
#     command: --host web --env proxyUrl=http://api:5000
#     depends_on:
#      - "api" # make sure API is up so that proxy doesn't fail
