name: Benchmarks (.NET Core)

on:
  push:
    branches: [ master, release-*, benchmark-*]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'
  pull_request:
    branches: [ master, release-*, benchmark-*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet tool restore
      working-directory: ./dotnet-web-api/
    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
      working-directory: ./dotnet-web-api/
    - name: Run Tests
      run: dotnet test --no-restore --verbosity minimal
      working-directory: ./dotnet-web-api/
    - name: Run benchmarks
      run: dotnet dotnet-benchmark ./Prime.Service.Benchmarks/bin/Release/netstandard2.0/Prime.Service.Benchmarks.dll --filter '*' --runtimes net472 netcoreapp3.1
      working-directory: ./dotnet-web-api/
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Benchmarks
        path: ./dotnet-web-api/BenchmarkDotNet.Artifacts/
