name:  Unit Tests (.NET Core)

on:
  push:
    paths:
    - 'dotnet-web-api/**'
    - '.github/**' # run if CI/CD config changes
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./aurelia-spa/
    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
      working-directory: ./aurelia-spa/
    - name: Run Tests
      run: dotnet test --no-restore --verbosity minimal
      working-directory: ./aurelia-spa/
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: dotnet-web-api
        path:  dotnet-web-api/Prime.WebApi/bin/Release/netcoreapp3.1/
